-- Yomu//Reviews Migration Script
-- Paste this into: Supabase Dashboard > SQL Editor > New Query > Run

-- Step 1: Enable RLS (Row Level Security) on the reviews table
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

-- Step 2: Allow anyone to READ reviews (public access)
CREATE POLICY "Anyone can read reviews"
ON reviews FOR SELECT
TO anon, authenticated
USING (true);

-- Step 3: Only logged-in users can INSERT reviews
CREATE POLICY "Authenticated users can insert reviews"
ON reviews FOR INSERT
TO authenticated
WITH CHECK (true);

-- Step 4: Only logged-in users can UPDATE reviews
CREATE POLICY "Authenticated users can update reviews"
ON reviews FOR UPDATE
TO authenticated
USING (true);

-- Step 5: Only logged-in users can DELETE reviews
CREATE POLICY "Authenticated users can delete reviews"
ON reviews FOR DELETE
TO authenticated
USING (true);

-- Step 6: Insert all existing reviews
INSERT INTO reviews (title, author, artist, status, genre, rating, gist, image_url, overview, story, art, characters, verdict) VALUES

('Solo Leveling', 'Chugong', 'Jang Sung-rak (DUBU)', 'Completed', 'Action, Fantasy', 4, 'The weakest hunter becomes the strongest...', 'https://m.media-amazon.com/images/I/81OYRZEQG7L._AC_UF1000,1000_QL80_.jpg',
'Solo Leveling is one of the most iconic manhwa titles to come out of South Korea, and for good reason. Based on the web novel by Chugong, it follows Sung Jinwoo, a hunter ranked as the weakest of them all in a world where mysterious gates connect Earth to dangerous dungeons full of monsters. After a near-death experience in a particularly deadly dungeon, Jinwoo awakens with a unique ability that sets him apart from every other hunter: the power to level up. What follows is an incredibly satisfying power fantasy that took the manhwa community by storm, blending RPG-inspired mechanics with high-octane action from start to finish.',
'The story of Solo Leveling is straightforward but effective. It thrives on its power fantasy premise — watching Jinwoo grow from the weakest hunter into an unstoppable force is endlessly entertaining. The pacing is relentless; nearly every chapter delivers a fight, a power-up, or a revelation that keeps you scrolling. The world-building is a strong point, with a well-constructed ranking system, dungeon mechanics, and a larger cosmic mythology that gradually unfolds as Jinwoo grows stronger. Some may find the arc structure a bit repetitive — Jinwoo enters a dungeon, dominates everyone, levels up, repeat — but if you buy into the premise, it never gets old. The story does lose a bit of momentum in its later stretch, and the ending may feel abrupt for some, but it wraps things up without leaving major loose ends.',
'This is where Solo Leveling truly shines. The artwork by DUBU (Jang Sung-rak) is nothing short of breathtaking. Every action panel is drawn with cinematic intensity — the scale of fights, the fluidity of movement, and the sheer level of detail in each frame are top-tier even by manhwa standards. The use of shadows, lighting effects, and dynamic angles makes every encounter feel like a blockbuster moment. Character designs are sharp and memorable, and the monster designs range from intimidating to genuinely terrifying. It is no exaggeration to say that Solo Leveling''s art alone is worth the read. This is one of the most visually stunning action manhwa you will ever come across.',
'Sung Jinwoo is the heart and soul of this series. He starts as an endearing underdog and gradually transforms into a cool, confident powerhouse — and that transformation is one of the most satisfying character arcs in the genre. However, where the series falters slightly is with its supporting cast. Because Jinwoo outpaces everyone so quickly, many side characters become irrelevant or fade into the background. There are standout supporting characters who leave an impression, but in general, Solo Leveling is very much a one-man show. The villains, on the other hand, bring genuine presence and threat when they appear, and the series does a great job building up its antagonists even if their time on screen is often limited.',
'Solo Leveling is the definitive power fantasy manhwa. It delivers exactly what it promises — jaw-dropping art, exhilarating action, and the deep satisfaction of watching an underdog become the strongest. While the side characters and story structure could use more depth, the sheer momentum and visual spectacle of this series make it an absolute must-read for any action fan. If you have never read a manhwa before, this is the one to start with. It earned its reputation for a reason.'),

('Eleceed', 'Son Jae-ho', 'ZHENA', 'Completed', 'Action, Fantasy, Adventure', 5, 'A high school student with a secret ability to read minds...', 'https://static.wikia.nocookie.net/eleceed/images/3/3a/Eleceed_cover.jpg/revision/latest?cb=20260217191546',
'Eleceed is a manhwa that masterfully blends action, comedy, and heart in a way that few series manage to pull off. Created by the duo of Son Jae-ho (known for Noblesse) and artist ZHENA, it follows Jiwoo Seo, a kind-hearted high school student with superhuman speed, and Kayden Break, a powerful awakener currently stuck in the body of a fat cat. Their unlikely partnership kicks off a story that is equal parts hilarious and thrilling. Eleceed quickly became a fan favorite in the webtoon community for its likeable characters, clean humor, and consistently exciting fights.',
'Eleceed''s story unfolds at a comfortable pace that never feels rushed or dragged out. It begins with a relatively simple setup — Jiwoo discovering the world of awakeners through Kayden — and gradually expands into a much larger narrative involving powerful organizations, rival academies, and world-level threats. What makes Eleceed''s story stand out is that it never takes itself too seriously. There is a perfect balance between intense action arcs and lighthearted, comedic downtime. The training arcs are satisfying, the tournaments are hype, and the stakes escalate naturally without feeling forced. The series also handles its power scaling remarkably well, always giving you a reason to look forward to the next fight.',
'ZHENA''s art in Eleceed is clean, vibrant, and incredibly polished. The character designs are attractive and distinct — you will never confuse one character for another. The action sequences are fluid and dynamic, with excellent use of speed lines and impact frames that make Jiwoo''s lightning-fast movements feel genuinely exciting. The expressions during comedic moments are also top-notch; the way characters react with exaggerated shock or deadpan delivery adds so much to the humor. The art only gets better as the series progresses, with later arcs featuring some truly stunning fight choreography.',
'The characters are Eleceed''s greatest strength. Jiwoo is one of the most genuinely likeable protagonists in any manhwa — he is kind, brave, and earnest without being naive. Kayden, as both a mentor and a comedic presence, is an absolute scene-stealer; his dynamic with Jiwoo is the backbone of the series. The supporting cast is equally strong: the group of friends Jiwoo assembles at the academy each have distinct personalities and abilities, and the series gives them room to shine individually. Even the antagonists are well-written, with clear motivations and varying degrees of menace. The mentor-student relationships in this series are particularly well-done and emotionally resonant.',
'Eleceed is a near-perfect manhwa. It has everything — incredible action, genuine humor, loveable characters, and beautiful art. It is the kind of series that puts a smile on your face every time you read a new chapter. Whether you are a long-time manhwa reader or just getting started, Eleceed is an absolute must-read. It earns every bit of its stellar reputation and stands as one of the best action-comedy webtoons ever made.'),

('Omniscient Reader''s Viewpoint', 'Sing Shong', 'Sleepy-C', 'Ongoing', 'Action, Fantasy, Apocalyptic', 4.5, 'The only reader who knows the novel''s ending...', 'https://static.wikia.nocookie.net/omniscient-readers-viewpoint/images/1/1d/Volume_3-newcover.jpg/revision/latest?cb=20230527065605',
'Omniscient Reader''s Viewpoint (ORV) is not your typical apocalyptic fantasy manhwa. Based on the acclaimed web novel by Sing Shong, it tells the story of Kim Dokja, an ordinary office worker whose one defining trait is that he is the sole reader who finished a particular web novel called "Three Ways to Survive the Apocalypse." When the events of that novel suddenly become reality, Dokja finds himself uniquely equipped to navigate this new, deadly world — not because he is the strongest, but because he knows the story. It is a brilliant premise that elevates ORV far above the standard survival-game genre.',
'ORV''s story is extraordinarily ambitious in scope. It starts as what appears to be a survival scenario with system-like mechanics — scenarios, constellations, and probability — but steadily reveals itself to be a deeply layered narrative about stories, fate, and what it means to be a reader versus a protagonist. The writing is dense and intelligent; every arc builds on the last, with foreshadowing that pays off chapters or even arcs later. The world-building is expansive and creative, blending mythology, meta-narrative concepts, and apocalyptic stakes in a way that feels entirely fresh. If you enjoy stories that challenge you to think and reward you for paying attention, ORV delivers in spades.',
'Sleepy-C''s artwork for the manhwa adaptation does a commendable job of translating the source material''s epic scale to a visual medium. The action scenes are dynamic and well-choreographed, with strong use of color and composition during key moments. Character designs are distinctive and expressive, particularly during emotional or dramatic scenes. While the art may not reach the sheer visual spectacle of some other action manhwa, it more than compensates with its storytelling clarity and atmospheric paneling.',
'Kim Dokja is one of the most compelling protagonists in modern manhwa. He is not the strongest or the most charismatic in the traditional sense, but his intelligence, quiet determination, and the subtle emotional depth beneath his calm exterior make him fascinating to follow. He is a character who carries the weight of knowing too much, and the series explores what that burden does to a person beautifully. The supporting cast is equally remarkable — each companion has a fully realized personality, distinct motivations, and genuine growth throughout the story.',
'Omniscient Reader''s Viewpoint is a masterclass in storytelling. It takes a familiar genre and transforms it into something truly unique through its meta-narrative premise, complex characters, and layered writing. It is not the fastest read — the story demands your attention and patience — but the payoff is immense. If you are looking for a manhwa that is as intellectually engaging as it is emotionally resonant, ORV is one of the best in the medium.'),

('Teenage Mercenary', 'YC', 'Rakyeon', 'Ongoing', 'Action', 4, 'A boy who was a child soldier for 10 years...', 'https://preview.redd.it/mercenary-enrolment-people-keep-suggesting-me-to-read-this-v0-1jg9d3jr0fya1.png?auto=webp&s=821320bac1266c8ace42f93d1381a7cd0bc3f87c',
'Teenage Mercenary (also known as Mercenary Enrollment) is an action manhwa that hooks you with a simple but compelling premise: a boy who spent a decade as a child soldier on the battlefield is finally reunited with his family and must now navigate the equally treacherous world of high school. Written by YC and illustrated by Rakyeon, this series blends raw combat with surprisingly touching family moments, creating a reading experience that is both adrenaline-pumping and heartfelt.',
'The story follows Ijin Yu, a young man with elite combat training who returns to civilian life after years as a mercenary. He enrolls in a regular high school to be close to his grandfather and younger sister, but his past and his extraordinary skills make it impossible to live a quiet life. The plot does a great job of balancing school life with action — Ijin''s attempts at normalcy are constantly interrupted by threats ranging from school bullies to organized crime, and each arc raises the stakes appropriately.',
'Rakyeon''s art is clean and effective, particularly during fight scenes. The action choreography is one of the series'' highlights — Ijin''s fighting style feels grounded and tactical, more akin to military combat than flashy superpowers, and the art reflects that with sharp, efficient panels. Character designs are good, though not groundbreaking, and the overall visual quality is consistent throughout.',
'Ijin Yu is a protagonist who works because of his contrast. He is a stone-cold fighter on the battlefield but genuinely awkward and soft-hearted around his family. His relationship with his younger sister Yuna is the emotional core of the series, and it is surprisingly well-written — their bond feels real and gives Ijin a clear motivation that goes beyond just being strong.',
'Teenage Mercenary is a solid action manhwa that delivers exactly what you want: a capable protagonist with a cool backstory, well-choreographed fights, and enough emotional depth to keep you invested beyond the action. It does not reinvent the genre, but it executes its formula with confidence and consistency.'),

('Nano Machine', 'Han Joong Wol Ya', 'Geum Gang Bul Goe', 'Ongoing', 'Action, Fantasy, Adventure', 4.5, 'A young boy with a nano machine in his body...', 'https://preview.redd.it/nano-machine-is-it-really-that-good-v0-4u9tr29hxumc1.jpeg?auto=webp&s=05de401fb51bbf8660b5a9d52dc376f60e816af8',
'Nano Machine takes the martial arts murim genre and injects it with a futuristic twist that makes it stand out from the crowd. Written by Han Joong Wol Ya and illustrated by Geum Gang Bul Goe, it follows Cheon Yeo-woon, a lowly prince in a powerful martial arts clan who is looked down upon by everyone due to his humble origins. Everything changes when a descendant from the distant future implants a nano machine into his body, giving him access to technology far beyond his era.',
'The story of Nano Machine is a satisfying blend of martial arts academy life, clan politics, and escalating power struggles. The nano machine element adds a unique strategic layer — Yeo-woon does not just get stronger through training alone; he uses the nano machine to analyze techniques, heal injuries, and gain tactical advantages that feel clever rather than cheap. The academy arc is particularly engaging, with a tournament-style structure that keeps the tension high.',
'The art in Nano Machine is strong, especially during combat sequences. The martial arts choreography is detailed and impactful, with each technique feeling weighty and visually distinct. Character designs are solid, with particularly good work on the various clan elders and antagonists who each have a menacing and memorable look.',
'Cheon Yeo-woon is a protagonist who earns his growth. Despite having the nano machine as an advantage, the series makes it clear that his determination and combat instincts are what truly set him apart. He is calculated, ruthless when necessary, and deeply loyal to those who earn his trust. The dynamic between him and his gradually growing circle of allies is one of the series'' strengths.',
'Nano Machine is a must-read for fans of martial arts manhwa. It successfully combines the traditional murim genre with a sci-fi twist that never feels gimmicky, and delivers a protagonist whose rise to power is both strategic and earned.'),

('That Time I Got Reincarnated As A Slime', 'Fuse', 'Taiki Kawakami', 'Ongoing', 'Action, Fantasy, Adventure, Isekai', 4.5, 'A salaryman gets reincarnated as a slime...', 'https://m.media-amazon.com/images/M/MV5BM2IwMDM4MDgtZWU2Zi00YjA2LWJhOTItNGUzMWM1N2E4ZTk3XkEyXkFqcGc@._V1_.jpg',
'That Time I Got Reincarnated As A Slime is one of the most beloved isekai series in modern manga and light novel history. Written by Fuse and illustrated by Taiki Kawakami, it follows a salaryman who, after an untimely death, is reincarnated in a fantasy world as a slime — one of the weakest creatures in any RPG. But this is no ordinary slime. Armed with the unique ability to absorb and mimic anything it consumes, our protagonist Rimuru Tempest quickly becomes one of the most powerful beings in the world.',
'What makes Slime''s story special is that it is not really about defeating a demon lord or saving the world in the traditional sense. Instead, the heart of the series lies in Rimuru''s quest to build a nation where all races — humans, goblins, orcs, dwarves, and more — can coexist peacefully. This nation-building focus gives the story a unique, almost cozy feel that sets it apart from more combat-heavy isekai.',
'Taiki Kawakami''s art does a solid job bringing the world of Slime to life. The character designs are charming and varied — from Rimuru''s adorable slime form to the diverse cast of monsters and humans, everyone is visually distinct. The action sequences are competent, though they can sometimes lack the raw impact of more action-focused manga. Where the art truly shines is in its world-building panels.',
'Rimuru is an incredibly likeable protagonist. Unlike many isekai leads who are defined solely by their power, Rimuru''s greatest strength is his personality — he is reasonable, compassionate, and genuinely wants to create a better world for everyone around him. His leadership style is inclusive and pragmatic, which makes his nation-building efforts feel earned rather than handed to him.',
'That Time I Got Reincarnated As A Slime is a must-read for isekai fans and a great entry point for newcomers to the genre. It offers something genuinely different from the standard isekai formula — a focus on community, diplomacy, and world-building that makes it feel more like a fantasy nation simulator than a power fantasy.'),

('Tokyo Revengers', 'Ken Wakui', 'Ken Wakui', 'Completed', 'Action, Drama, Supernatural', 4, 'A man goes back in time to save his ex-girlfriend...', 'https://upload.wikimedia.org/wikipedia/en/b/b1/Tokyo_Revengers_volume_1_cover.jpg',
'Tokyo Revengers by Ken Wakui is a manga that grabs you with a gripping premise and refuses to let go — at least for a while. It follows Takemichi Hanagaki, a down-on-his-luck twenty-something who discovers he can leap back in time to his middle school years. His mission: to change the past and save his ex-girlfriend from a tragic fate tied to the notorious Tokyo Manji Gang.',
'Tokyo Revengers'' story is a rollercoaster. The time-travel mechanic creates a compelling loop: Takemichi travels back, tries to change events, returns to the present to see the consequences, and discovers things have gone wrong in new ways. This structure keeps the tension incredibly high and makes every arc feel like a puzzle to solve. The delinquent gang dynamics add a layer of raw energy.',
'Ken Wakui''s art is rough around the edges but effective. The character designs are distinct and memorable — you can always tell who is who even in the large cast of gang members. The art excels in its emotional moments; facial expressions during dramatic reveals or heartbreaking scenes are drawn with genuine intensity.',
'Takemichi is a polarizing protagonist. He is weak, emotional, and often in over his head — which can be frustrating for readers used to competent leads. But that is also what makes him compelling. His courage comes not from strength but from sheer desperation and love for the people he is trying to save. The real stars, however, are the gang leaders and members.',
'Tokyo Revengers is a series of spectacular highs and frustrating lows. When it works, it is one of the most gripping manga you will ever read — the combination of time-travel stakes and delinquent drama creates something truly unique. If you can accept that the journey is better than the destination, Tokyo Revengers is an emotional ride unlike anything else in manga.'),

('Swordmaster''s Youngest Son', 'Emperor Penguin', 'RAN', 'Ongoing', 'Action, Fantasy, Adventure', 5, 'The youngest son of a legendary swordsman...', 'https://i.redd.it/vcymnb6yquw81.jpg',
'Swordmaster''s Youngest Son is a manhwa that takes the regression genre and executes it with an impressive level of polish and depth. Based on the web novel by Emperor Penguin, it follows Jin Runcandel, the youngest son of the legendary Runcandel swordmaster family, who is given a second chance at life after meeting a tragic end.',
'The story of Swordmaster''s Youngest Son is a masterclass in the regression subgenre. What sets it apart from similar titles is the depth of its world-building and political intrigue. The Runcandel family is not just a backdrop — it is a sprawling, complex power structure with its own internal politics, rivalries, and traditions.',
'RAN''s art in Swordmaster''s Youngest Son is excellent. The character designs are sharp and regal, perfectly capturing the aristocratic atmosphere of the Runcandel family. The swordfighting sequences are beautifully choreographed, with each technique feeling powerful and distinct.',
'Jin Runcandel is a protagonist who stands out in a genre full of regression leads. He is intelligent, strategic, and patient — traits that make his rise to power feel earned and satisfying. Unlike many regression protagonists who simply overpower everyone with future knowledge, Jin uses his second chance wisely.',
'Swordmaster''s Youngest Son is one of the best regression manhwa available. It combines excellent world-building, deep political intrigue, stunning art, and a protagonist who genuinely earns his victories. Highly recommended for fans of fantasy and political drama alike.'),

('Star Embracing Swordmaster', 'Hanon', 'Vantas', 'Ongoing', 'Action, Fantasy, Adventure', 5, 'A young boy with a mysterious past...', 'https://i.redd.it/z63xjceq2z1d1.jpeg',
'Star Embracing Swordmaster is a manhwa that quietly rose to become one of the most consistently impressive fantasy action series in the webtoon space. Written by Hanon and illustrated by Vantas, it follows a young protagonist navigating a world where martial arts and celestial powers intertwine.',
'Star Embracing Swordmaster''s story is one of steady escalation done right. The series begins with a relatively grounded setup and gradually expands its scope to encompass larger, more cosmic conflicts. What makes the story compelling is the way it weaves martial arts progression with a broader narrative about power, destiny, and the nature of strength.',
'Vantas delivers some of the best art in the manhwa space with Star Embracing Swordmaster. The action sequences are breathtaking — swordfighting is rendered with incredible precision and dynamism, and the celestial/star-based powers are depicted with a visual grandeur that is genuinely awe-inspiring.',
'The protagonist of Star Embracing Swordmaster is a standout. He is driven, talented, and grows in ways that feel natural and earned — you believe in his journey because the series puts in the work to show every step of his development.',
'Star Embracing Swordmaster is a must-read for fans of martial arts and fantasy manhwa. It combines stunning art, excellent pacing, and a deeply satisfying growth narrative into one of the most polished packages in the genre.'),

('The Greatest Estate Developer', 'Lee Hyunmin', 'Kim Hyunsoo', 'Ongoing', 'Fantasy, Adventure, Comedy', 5, 'A man with a talent for engineering...', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1725185056i/218343539.jpg',
'The Greatest Estate Developer is a manhwa that answers the question nobody knew they needed answered: what if an isekai protagonist used civil engineering to save the world? Written by Lee Hyunmin and illustrated by Kim Hyunsoo, this series follows a man who is reincarnated into a fantasy novel as the wastrel son of a noble family.',
'The story of The Greatest Estate Developer is brilliantly unconventional. The protagonist knows the plot of the novel he has been isekai''d into, including the disasters that are about to befall his territory. His solution? Build infrastructure. Construct flood barriers. Design water systems. Negotiate trade deals.',
'Kim Hyunsoo''s art is clean, expressive, and perfectly suited to the series'' tone. The character designs are appealing, and the facial expressions during comedic moments are consistently hilarious — perfectly timed deadpan reactions and exaggerated shock faces that enhance every joke.',
'The protagonist is the series'' biggest asset. He is resourceful, witty, and endlessly entertaining to watch. His approach to every problem — applying modern engineering knowledge to a fantasy world — creates comedy gold, and his growing confidence as an estate developer is surprisingly compelling.',
'The Greatest Estate Developer is a breath of fresh air in the isekai genre. It proves that you do not need a sword or superpowers to be compelling — sometimes all you need is a good blueprint and a can-do attitude. It is one of the most original and entertaining series in the genre.'),

('Frieren: Beyond Journey''s End', 'Kanehito Yamada', 'Tsukasa Abe', 'Ongoing', 'Fantasy, Adventure, Action', 5, 'An elf''s journey to understand humans...', 'https://m.media-amazon.com/images/M/MV5BZTI4ZGMxN2UtODlkYS00MTBjLWE1YzctYzc3NDViMGI0ZmJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
'Frieren: Beyond Journey''s End is a manga that redefines what a fantasy story can be. Written by Kanehito Yamada and illustrated by Tsukasa Abe, it follows Frieren, an elf mage who was part of the hero''s party that defeated the Demon King. The story begins after the victory, exploring what happens when an immortal being watches her mortal companions age and pass away.',
'Frieren''s story is unconventional and all the better for it. It takes place after the traditional fantasy adventure is already over, and instead of building toward an epic climax, it unfolds as a series of reflective journeys. The pacing is deliberate and meditative, which may not suit everyone, but for those who connect with it, Frieren offers one of the most profoundly moving experiences in manga.',
'Tsukasa Abe''s art in Frieren is stunning. The fantasy world is rendered with breathtaking detail — lush forests, ancient ruins, vast landscapes — all depicted with a gentle, painterly quality that perfectly matches the series'' contemplative tone. This is one of the most visually beautiful manga being published today.',
'Frieren herself is one of the most unique protagonists in any manga. She is ancient, powerful, and initially appears emotionally detached — but the entire series is about watching her gradually understand the value of the connections she once took for granted. Fern, her apprentice, provides a wonderful grounding presence.',
'Frieren: Beyond Journey''s End is a masterpiece. It is a manga that proves fantasy does not need constant action or epic scale to be compelling — sometimes the most powerful stories are the quiet ones about an elf learning to appreciate the fleeting beauty of human life. If you read one fantasy manga this year, make it Frieren.'),

('Lookism', 'Park Tae-jun', 'Park Tae-jun', 'Completed', 'Drama, Action, Supernatural', 4.5, 'A bullied high school student...', 'https://i.pinimg.com/736x/bb/3c/f7/bb3cf78908440b3b06898fb0fd9935da.jpg',
'Lookism by Park Tae-jun is a manhwa that starts with one of the most provocative premises in the medium: what if an ugly, bullied teenager suddenly woke up in a second body — one that is tall, handsome, and athletic? The series uses this body-swap concept to explore themes of beauty standards, social hierarchy, discrimination, and identity in modern Korean society.',
'Lookism''s story can be divided into two distinct phases. The early chapters are focused on social commentary — exploring how people are treated differently based on their appearance, and how that shapes identity and self-worth. As the series progresses, it shifts heavily into action territory, with elaborate gang hierarchies and interconnected crews.',
'Park Tae-jun''s art in Lookism is distinctive and highly expressive. The character designs are immediately recognizable — the contrast between the protagonist''s two bodies is striking and serves as a constant visual reminder of the series'' core themes. The full-color webtoon format is used effectively throughout.',
'Lookism has one of the largest and most diverse casts in any manhwa. The protagonist, Daniel Park, is relatable in his insecurities and growth, and his dual existence gives the series a unique lens through which to examine its themes. The sheer number of well-developed characters in this series is genuinely impressive.',
'Lookism is a bold, ambitious manhwa that tackles real-world issues while delivering top-tier action and an enormous, well-developed cast. If you are looking for a manhwa that has something to say about society while also delivering incredible fights and memorable characters, Lookism is a remarkable achievement.');

-- IMPORTANT: After running this script, create your admin account:
-- Go to Supabase Dashboard > Authentication > Users > Add User
-- Enter your email and password, then use those to log in on admin.html
